((generic_command
   command: (command_name)
   arg: (curly_group)) @conceal
 (#lua-match? @conceal "\\dot{[a-zA-Z]}")
 (#set-pairs! @conceal conceal
  "\\dot{a}" "ȧ"
  "\\dot{b}" "ḃ"
  "\\dot{c}" "ċ"
  "\\dot{d}" "ḋ"
  "\\dot{e}" "ė"
  "\\dot{f}" "ḟ"
  "\\dot{g}" "ġ"
  "\\dot{h}" "ḣ"
  "\\dot{i}" "i̇"
  "\\dot{j}" "j̇"
  "\\dot{k}" "k̇"
  "\\dot{l}" "l̇"
  "\\dot{m}" "ṁ"
  "\\dot{n}" "ṅ"
  "\\dot{o}" "ȯ"
  "\\dot{p}" "ṗ"
  "\\dot{q}" "q̇"
  "\\dot{r}" "ṙ"
  "\\dot{s}" "ṡ"
  "\\dot{t}" "ṫ"
  "\\dot{u}" "u̇"
  "\\dot{v}" "v̇"
  "\\dot{w}" "ẇ"
  "\\dot{x}" "ẋ"
  "\\dot{y}" "ẏ"
  "\\dot{z}" "ż"
  "\\dot{A}" "Ȧ"
  "\\dot{B}" "Ḃ"
  "\\dot{C}" "Ċ"
  "\\dot{D}" "Ḋ"
  "\\dot{E}" "Ė"
  "\\dot{F}" "Ḟ"
  "\\dot{G}" "Ġ"
  "\\dot{H}" "Ḣ"
  "\\dot{I}" "İ"
  "\\dot{J}" "J̇"
  "\\dot{K}" "K̇"
  "\\dot{L}" "L̇"
  "\\dot{M}" "Ṁ"
  "\\dot{N}" "Ṅ"
  "\\dot{O}" "Ȯ"
  "\\dot{P}" "Ṗ"
  "\\dot{Q}" "Q̇"
  "\\dot{R}" "Ṙ"
  "\\dot{S}" "Ṡ"
  "\\dot{T}" "Ṫ"
  "\\dot{U}" "U̇"
  "\\dot{V}" "V̇"
  "\\dot{W}" "Ẇ"
  "\\dot{X}" "Ẋ"
  "\\dot{Y}" "Ẏ"
  "\\dot{Z}" "Ż"))

((generic_command
   command: (command_name)
   arg: (curly_group)) @conceal
 (#lua-match? @conceal "\\dot{\\[a-zA-Z]+}")
 (#set! priority 101)
 (#set-pairs! @conceal conceal
  ; Greek letters (lowercase)
  "\\dot{\\alpha}" "α̇"
  "\\dot{\\beta}" "β̇"
  "\\dot{\\gamma}" "γ̇"
  "\\dot{\\delta}" "δ̇"
  "\\dot{\\epsilon}" "ε̇"
  "\\dot{\\zeta}" "ζ̇"
  "\\dot{\\eta}" "η̇"
  "\\dot{\\theta}" "θ̇"
  "\\dot{\\iota}" "ι̇"
  "\\dot{\\kappa}" "κ̇"
  "\\dot{\\lambda}" "λ̇"
  "\\dot{\\mu}" "μ̇"
  "\\dot{\\nu}" "ν̇"
  "\\dot{\\xi}" "ξ̇"
  "\\dot{\\omicron}" "ο̇"
  "\\dot{\\pi}" "π̇"
  "\\dot{\\rho}" "ρ̇"
  "\\dot{\\sigma}" "σ̇"
  "\\dot{\\tau}" "τ̇"
  "\\dot{\\upsilon}" "υ̇"
  "\\dot{\\phi}" "ϕ̇"
  "\\dot{\\chi}" "χ̇"
  "\\dot{\\psi}" "ψ̇"
  "\\dot{\\omega}" "ω̇"
  
  ; Greek letters (uppercase)
  "\\dot{\\Alpha}" "Α̇"
  "\\dot{\\Beta}" "Β̇"
  "\\dot{\\Gamma}" "Γ̇"
  "\\dot{\\Delta}" "Δ̇"
  "\\dot{\\Epsilon}" "Ε̇"
  "\\dot{\\Zeta}" "Ζ̇"
  "\\dot{\\Eta}" "Η̇"
  "\\dot{\\Theta}" "Θ̇"
  "\\dot{\\Iota}" "Ι̇"
  "\\dot{\\Kappa}" "Κ̇"
  "\\dot{\\Lambda}" "Λ̇"
  "\\dot{\\Mu}" "Μ̇"
  "\\dot{\\Nu}" "Ν̇"
  "\\dot{\\Xi}" "Ξ̇"
  "\\dot{\\Omicron}" "Ο̇"
  "\\dot{\\Pi}" "Π̇"
  "\\dot{\\Rho}" "Ρ̇"
  "\\dot{\\Sigma}" "Σ̇"
  "\\dot{\\Tau}" "Τ̇"
  "\\dot{\\Upsilon}" "Υ̇"
  "\\dot{\\Phi}" "Φ̇"
  "\\dot{\\Chi}" "Χ̇"
  "\\dot{\\Psi}" "Ψ̇"
  "\\dot{\\Omega}" "Ω̇"
  
  ; Variants and alternate forms
  "\\dot{\\varepsilon}" "ϵ̇"
  "\\dot{\\vartheta}" "ϑ̇"
  "\\dot{\\varpi}" "ϖ̇"
  "\\dot{\\varrho}" "ϱ̇"
  "\\dot{\\varsigma}" "ς̇"
  "\\dot{\\varphi}" "φ̇"))

((generic_command
   command: (command_name)
   arg: (curly_group)) @conceal
 (#lua-match? @conceal "\\dot{\\mathbf{[a-zA-Z]}}")
 (#set! priority 101)
 (#set-pairs! @conceal conceal
   "\\dot{\\mathbf{A}}" "𝐀̇"
   "\\dot{\\mathbf{B}}" "𝐁̇"
   "\\dot{\\mathbf{C}}" "𝐂̇"
   "\\dot{\\mathbf{D}}" "𝐃̇"
   "\\dot{\\mathbf{E}}" "𝐄̇"
   "\\dot{\\mathbf{F}}" "𝐅̇"
   "\\dot{\\mathbf{G}}" "𝐆̇"
   "\\dot{\\mathbf{H}}" "𝐇̇"
   "\\dot{\\mathbf{I}}" "𝐈̇"
   "\\dot{\\mathbf{J}}" "𝐉̇"
   "\\dot{\\mathbf{K}}" "𝐊̇"
   "\\dot{\\mathbf{L}}" "𝐋̇"
   "\\dot{\\mathbf{M}}" "𝐌̇"
   "\\dot{\\mathbf{N}}" "𝐍̇"
   "\\dot{\\mathbf{O}}" "𝐎̇"
   "\\dot{\\mathbf{P}}" "𝐏̇"
   "\\dot{\\mathbf{Q}}" "𝐐̇"
   "\\dot{\\mathbf{R}}" "𝐑̇"
   "\\dot{\\mathbf{S}}" "𝐒̇"
   "\\dot{\\mathbf{T}}" "𝐓̇"
   "\\dot{\\mathbf{U}}" "𝐔̇"
   "\\dot{\\mathbf{V}}" "𝐕̇"
   "\\dot{\\mathbf{W}}" "𝐖̇"
   "\\dot{\\mathbf{X}}" "𝐗̇"
   "\\dot{\\mathbf{Y}}" "𝐘̇"
   "\\dot{\\mathbf{Z}}" "𝐙̇"
   "\\dot{\\mathbf{a}}" "𝐚̇"
   "\\dot{\\mathbf{b}}" "𝐛̇"
   "\\dot{\\mathbf{c}}" "𝐜̇"
   "\\dot{\\mathbf{d}}" "𝐝̇"
   "\\dot{\\mathbf{e}}" "𝐞̇"
   "\\dot{\\mathbf{f}}" "𝐟̇"
   "\\dot{\\mathbf{g}}" "𝐠̇"
   "\\dot{\\mathbf{h}}" "𝐡̇"
   "\\dot{\\mathbf{i}}" "𝐢̇"
   "\\dot{\\mathbf{j}}" "𝐣̇"
   "\\dot{\\mathbf{k}}" "𝐤̇"
   "\\dot{\\mathbf{l}}" "𝐥̇"
   "\\dot{\\mathbf{m}}" "𝐦̇"
   "\\dot{\\mathbf{n}}" "𝐧̇"
   "\\dot{\\mathbf{o}}" "𝐨̇"
   "\\dot{\\mathbf{p}}" "𝐩̇"
   "\\dot{\\mathbf{q}}" "𝐪̇"
   "\\dot{\\mathbf{r}}" "𝐫̇"
   "\\dot{\\mathbf{s}}" "𝐬̇"
   "\\dot{\\mathbf{t}}" "𝐭̇"
   "\\dot{\\mathbf{u}}" "𝐮̇"
   "\\dot{\\mathbf{v}}" "𝐯̇"
   "\\dot{\\mathbf{w}}" "𝐰̇"
   "\\dot{\\mathbf{x}}" "𝐱̇"
   "\\dot{\\mathbf{y}}" "𝐲̇"
   "\\dot{\\mathbf{z}}" "𝐳̇"))
