((generic_command
   command: (command_name)
   arg: (curly_group)) @conceal
 (#lua-match? @conceal "\\bar{[a-zA-Z]}")
 (#set-pairs! @conceal conceal
  "\\bar{a}" "a̅"
  "\\bar{b}" "b̅"
  "\\bar{c}" "c̅"
  "\\bar{d}" "d̅"
  "\\bar{e}" "e̅"
  "\\bar{f}" "f̅"
  "\\bar{g}" "g̅"
  "\\bar{h}" "h̅"
  "\\bar{i}" "i̅"
  "\\bar{j}" "j̅"
  "\\bar{k}" "k̅"
  "\\bar{l}" "l̅"
  "\\bar{m}" "m̅"
  "\\bar{n}" "n̅"
  "\\bar{o}" "o̅"
  "\\bar{p}" "p̅"
  "\\bar{q}" "q̅"
  "\\bar{r}" "r̅"
  "\\bar{s}" "s̅"
  "\\bar{t}" "t̅"
  "\\bar{u}" "u̅"
  "\\bar{v}" "v̅"
  "\\bar{w}" "w̅"
  "\\bar{x}" "x̅"
  "\\bar{y}" "y̅"
  "\\bar{z}" "z̅"
  "\\bar{A}" "A̅"
  "\\bar{B}" "B̅"
  "\\bar{C}" "C̅"
  "\\bar{D}" "D̅"
  "\\bar{E}" "E̅"
  "\\bar{F}" "F̅"
  "\\bar{G}" "G̅"
  "\\bar{H}" "H̅"
  "\\bar{I}" "I̅"
  "\\bar{J}" "J̅"
  "\\bar{K}" "K̅"
  "\\bar{L}" "L̅"
  "\\bar{M}" "M̅"
  "\\bar{N}" "N̅"
  "\\bar{O}" "O̅"
  "\\bar{P}" "P̅"
  "\\bar{Q}" "Q̅"
  "\\bar{R}" "R̅"
  "\\bar{S}" "S̅"
  "\\bar{T}" "T̅"
  "\\bar{U}" "U̅"
  "\\bar{V}" "V̅"
  "\\bar{W}" "W̅"
  "\\bar{X}" "X̅"
  "\\bar{Y}" "Y̅"
  "\\bar{Z}" "Z̅"))

((generic_command
   command: (command_name)
   arg: (curly_group)) @conceal
 (#lua-match? @conceal "\\bar{\\\\[a-zA-Z]+}")
 (#set! priority 101)
 (#set-pairs! @conceal conceal
  ; Lowercase Greek letters (using combining macron U+0304)
  "\\bar{\\alpha}" "α̅"
  "\\bar{\\beta}" "β̅"
  "\\bar{\\gamma}" "γ̅"
  "\\bar{\\delta}" "δ̅"
  "\\bar{\\epsilon}" "ε̅"
  "\\bar{\\zeta}" "ζ̅"
  "\\bar{\\eta}" "η̅"
  "\\bar{\\theta}" "θ̅"
  "\\bar{\\iota}" "ι̅"
  "\\bar{\\kappa}" "κ̅"
  "\\bar{\\lambda}" "λ̅"
  "\\bar{\\mu}" "μ̅"
  "\\bar{\\nu}" "ν̅"
  "\\bar{\\xi}" "ξ̅"
  "\\bar{\\omicron}" "ο̅"
  "\\bar{\\pi}" "π̅"
  "\\bar{\\rho}" "ρ̅"
  "\\bar{\\sigma}" "σ̅"
  "\\bar{\\tau}" "τ̅"
  "\\bar{\\upsilon}" "υ̅"
  "\\bar{\\phi}" "ϕ̅"
  "\\bar{\\chi}" "χ̅"
  "\\bar{\\psi}" "ψ̅"
  "\\bar{\\omega}" "ω̅"
  
  ; Uppercase Greek letters
  "\\bar{\\Alpha}" "Α̅"
  "\\bar{\\Beta}" "Β̅"
  "\\bar{\\Gamma}" "Γ̅"
  "\\bar{\\Delta}" "Δ̅"
  "\\bar{\\Epsilon}" "Ε̅"
  "\\bar{\\Zeta}" "Ζ̅"
  "\\bar{\\Eta}" "Η̅"
  "\\bar{\\Theta}" "Θ̅"
  "\\bar{\\Iota}" "Ι̅"
  "\\bar{\\Kappa}" "Κ̅"
  "\\bar{\\Lambda}" "Λ̅"
  "\\bar{\\Mu}" "Μ̅"
  "\\bar{\\Nu}" "Ν̅"
  "\\bar{\\Xi}" "Ξ̅"
  "\\bar{\\Omicron}" "Ο̅"
  "\\bar{\\Pi}" "Π̅"
  "\\bar{\\Rho}" "Ρ̅"
  "\\bar{\\Sigma}" "Σ̅"
  "\\bar{\\Tau}" "Τ̅"
  "\\bar{\\Upsilon}" "Υ̅"
  "\\bar{\\Phi}" "Φ̅"
  "\\bar{\\Chi}" "Χ̅"
  "\\bar{\\Psi}" "Ψ̅"
  "\\bar{\\Omega}" "Ω̅"
  
  ; Variants and alternate forms
  "\\bar{\\varepsilon}" "ϵ̅"
  "\\bar{\\vartheta}" "ϑ̅"
  "\\bar{\\varpi}" "ϖ̅"
  "\\bar{\\varrho}" "ϱ̅"
  "\\bar{\\varsigma}" "ς̅"
  "\\bar{\\varphi}" "φ̅"))

((generic_command
   command: (command_name)
   arg: (curly_group)) @conceal
 (#lua-match? @conceal "\\bar{\\mathbf{[a-zA-Z]}}")
 (#set! priority 101)
 (#set-pairs! @conceal conceal
   "\\bar{\\mathbf{A}}" "𝐀̅"
   "\\bar{\\mathbf{B}}" "𝐁̅"
   "\\bar{\\mathbf{C}}" "𝐂̅"
   "\\bar{\\mathbf{D}}" "𝐃̅"
   "\\bar{\\mathbf{E}}" "𝐄̅"
   "\\bar{\\mathbf{F}}" "𝐅̅"
   "\\bar{\\mathbf{G}}" "𝐆̅"
   "\\bar{\\mathbf{H}}" "𝐇̅"
   "\\bar{\\mathbf{I}}" "𝐈̅"
   "\\bar{\\mathbf{J}}" "𝐉̅"
   "\\bar{\\mathbf{K}}" "𝐊̅"
   "\\bar{\\mathbf{L}}" "𝐋̅"
   "\\bar{\\mathbf{M}}" "𝐌̅"
   "\\bar{\\mathbf{N}}" "𝐍̅"
   "\\bar{\\mathbf{O}}" "𝐎̅"
   "\\bar{\\mathbf{P}}" "𝐏̅"
   "\\bar{\\mathbf{Q}}" "𝐐̅"
   "\\bar{\\mathbf{R}}" "𝐑̅"
   "\\bar{\\mathbf{S}}" "𝐒̅"
   "\\bar{\\mathbf{T}}" "𝐓̅"
   "\\bar{\\mathbf{U}}" "𝐔̅"
   "\\bar{\\mathbf{V}}" "𝐕̅"
   "\\bar{\\mathbf{W}}" "𝐖̅"
   "\\bar{\\mathbf{X}}" "𝐗̅"
   "\\bar{\\mathbf{Y}}" "𝐘̅"
   "\\bar{\\mathbf{Z}}" "𝐙̅"
   "\\bar{\\mathbf{a}}" "𝐚̅"
   "\\bar{\\mathbf{b}}" "𝐛̅"
   "\\bar{\\mathbf{c}}" "𝐜̅"
   "\\bar{\\mathbf{d}}" "𝐝̅"
   "\\bar{\\mathbf{e}}" "𝐞̅"
   "\\bar{\\mathbf{f}}" "𝐟̅"
   "\\bar{\\mathbf{g}}" "𝐠̅"
   "\\bar{\\mathbf{h}}" "𝐡̅"
   "\\bar{\\mathbf{i}}" "𝐢̅"
   "\\bar{\\mathbf{j}}" "𝐣̅"
   "\\bar{\\mathbf{k}}" "𝐤̅"
   "\\bar{\\mathbf{l}}" "𝐥̅"
   "\\bar{\\mathbf{m}}" "𝐦̅"
   "\\bar{\\mathbf{n}}" "𝐧̅"
   "\\bar{\\mathbf{o}}" "𝐨̅"
   "\\bar{\\mathbf{p}}" "𝐩̅"
   "\\bar{\\mathbf{q}}" "𝐪̅"
   "\\bar{\\mathbf{r}}" "𝐫̅"
   "\\bar{\\mathbf{s}}" "𝐬̅"
   "\\bar{\\mathbf{t}}" "𝐭̅"
   "\\bar{\\mathbf{u}}" "𝐮̅"
   "\\bar{\\mathbf{v}}" "𝐯̅"
   "\\bar{\\mathbf{w}}" "𝐰̅"
   "\\bar{\\mathbf{x}}" "𝐱̅"
   "\\bar{\\mathbf{y}}" "𝐲̅"
   "\\bar{\\mathbf{z}}" "𝐳̅"))

((generic_command
   command: (command_name)
   arg: (curly_group)) @conceal
 (#lua-match? @conceal "\\bar{\\mathbb{[A-Z]}}")
 (#set! priority 101)
 (#set-pairs! @conceal conceal
   "\\bar{\\mathbb{A}}" "𝔸̅"
   "\\bar{\\mathbb{B}}" "𝔹̅"
   "\\bar{\\mathbb{C}}" "ℂ̅"
   "\\bar{\\mathbb{D}}" "𝔻̅"
   "\\bar{\\mathbb{E}}" "𝔼̅"
   "\\bar{\\mathbb{F}}" "𝔽̅"
   "\\bar{\\mathbb{G}}" "𝔾̅"
   "\\bar{\\mathbb{H}}" "ℍ̅"
   "\\bar{\\mathbb{I}}" "𝕀̅"
   "\\bar{\\mathbb{J}}" "𝕁̅"
   "\\bar{\\mathbb{K}}" "𝕂̅"
   "\\bar{\\mathbb{L}}" "𝕃̅"
   "\\bar{\\mathbb{M}}" "𝕄̅"
   "\\bar{\\mathbb{N}}" "ℕ̅"
   "\\bar{\\mathbb{O}}" "𝕆̅"
   "\\bar{\\mathbb{P}}" "ℙ̅"
   "\\bar{\\mathbb{Q}}" "ℚ̅"
   "\\bar{\\mathbb{R}}" "ℝ̅"
   "\\bar{\\mathbb{S}}" "𝕊̅"
   "\\bar{\\mathbb{T}}" "𝕋̅"
   "\\bar{\\mathbb{U}}" "𝕌̅"
   "\\bar{\\mathbb{V}}" "𝕍̅"
   "\\bar{\\mathbb{W}}" "𝕎̅"
   "\\bar{\\mathbb{X}}" "𝕏̅"
   "\\bar{\\mathbb{Y}}" "𝕐̅"
   "\\bar{\\mathbb{Z}}" "ℤ̅"))

((generic_command
   command: (command_name)
   arg: (curly_group)) @conceal
 (#lua-match? @conceal "\\overline{[a-zA-Z]}")
 (#set-pairs! @conceal conceal
  "\\overline{a}" "a̅"
  "\\overline{b}" "b̅"
  "\\overline{c}" "c̅"
  "\\overline{d}" "d̅"
  "\\overline{e}" "e̅"
  "\\overline{f}" "f̅"
  "\\overline{g}" "g̅"
  "\\overline{h}" "h̅"
  "\\overline{i}" "i̅"
  "\\overline{j}" "j̅"
  "\\overline{k}" "k̅"
  "\\overline{l}" "l̅"
  "\\overline{m}" "m̅"
  "\\overline{n}" "n̅"
  "\\overline{o}" "o̅"
  "\\overline{p}" "p̅"
  "\\overline{q}" "q̅"
  "\\overline{r}" "r̅"
  "\\overline{s}" "s̅"
  "\\overline{t}" "t̅"
  "\\overline{u}" "u̅"
  "\\overline{v}" "v̅"
  "\\overline{w}" "w̅"
  "\\overline{x}" "x̅"
  "\\overline{y}" "y̅"
  "\\overline{z}" "z̅"
  "\\overline{A}" "A̅"
  "\\overline{B}" "B̅"
  "\\overline{C}" "C̅"
  "\\overline{D}" "D̅"
  "\\overline{E}" "E̅"
  "\\overline{F}" "F̅"
  "\\overline{G}" "G̅"
  "\\overline{H}" "H̅"
  "\\overline{I}" "I̅"
  "\\overline{J}" "J̅"
  "\\overline{K}" "K̅"
  "\\overline{L}" "L̅"
  "\\overline{M}" "M̅"
  "\\overline{N}" "N̅"
  "\\overline{O}" "O̅"
  "\\overline{P}" "P̅"
  "\\overline{Q}" "Q̅"
  "\\overline{R}" "R̅"
  "\\overline{S}" "S̅"
  "\\overline{T}" "T̅"
  "\\overline{U}" "U̅"
  "\\overline{V}" "V̅"
  "\\overline{W}" "W̅"
  "\\overline{X}" "X̅"
  "\\overline{Y}" "Y̅"
  "\\overline{Z}" "Z̅"))

((generic_command
   command: (command_name)
   arg: (curly_group)) @conceal
 (#lua-match? @conceal "\\overline{\\\\[a-zA-Z]+}")
 (#set! priority 101)
 (#set-pairs! @conceal conceal
  ; Lowercase Greek letters (using combining macron U+0304)
  "\\overline{\\alpha}" "α̅"
  "\\overline{\\beta}" "β̅"
  "\\overline{\\gamma}" "γ̅"
  "\\overline{\\delta}" "δ̅"
  "\\overline{\\epsilon}" "ε̅"
  "\\overline{\\zeta}" "ζ̅"
  "\\overline{\\eta}" "η̅"
  "\\overline{\\theta}" "θ̅"
  "\\overline{\\iota}" "ι̅"
  "\\overline{\\kappa}" "κ̅"
  "\\overline{\\lambda}" "λ̅"
  "\\overline{\\mu}" "μ̅"
  "\\overline{\\nu}" "ν̅"
  "\\overline{\\xi}" "ξ̅"
  "\\overline{\\omicron}" "ο̅"
  "\\overline{\\pi}" "π̅"
  "\\overline{\\rho}" "ρ̅"
  "\\overline{\\sigma}" "σ̅"
  "\\overline{\\tau}" "τ̅"
  "\\overline{\\upsilon}" "υ̅"
  "\\overline{\\phi}" "ϕ̅"
  "\\overline{\\chi}" "χ̅"
  "\\overline{\\psi}" "ψ̅"
  "\\overline{\\omega}" "ω̅"
  
  ; Uppercase Greek letters
  "\\overline{\\Alpha}" "Α̅"
  "\\overline{\\Beta}" "Β̅"
  "\\overline{\\Gamma}" "Γ̅"
  "\\overline{\\Delta}" "Δ̅"
  "\\overline{\\Epsilon}" "Ε̅"
  "\\overline{\\Zeta}" "Ζ̅"
  "\\overline{\\Eta}" "Η̅"
  "\\overline{\\Theta}" "Θ̅"
  "\\overline{\\Iota}" "Ι̅"
  "\\overline{\\Kappa}" "Κ̅"
  "\\overline{\\Lambda}" "Λ̅"
  "\\overline{\\Mu}" "Μ̅"
  "\\overline{\\Nu}" "Ν̅"
  "\\overline{\\Xi}" "Ξ̅"
  "\\overline{\\Omicron}" "Ο̅"
  "\\overline{\\Pi}" "Π̅"
  "\\overline{\\Rho}" "Ρ̅"
  "\\overline{\\Sigma}" "Σ̅"
  "\\overline{\\Tau}" "Τ̅"
  "\\overline{\\Upsilon}" "Υ̅"
  "\\overline{\\Phi}" "Φ̅"
  "\\overline{\\Chi}" "Χ̅"
  "\\overline{\\Psi}" "Ψ̅"
  "\\overline{\\Omega}" "Ω̅"
  
  ; Variants and alternate forms
  "\\overline{\\varepsilon}" "ϵ̅"
  "\\overline{\\vartheta}" "ϑ̅"
  "\\overline{\\varpi}" "ϖ̅"
  "\\overline{\\varrho}" "ϱ̅"
  "\\overline{\\varsigma}" "ς̅"
  "\\overline{\\varphi}" "φ̅"))

((generic_command
   command: (command_name)
   arg: (curly_group)) @conceal
 (#lua-match? @conceal "\\overline{\\mathbf{[a-zA-Z]}}")
 (#set! priority 101)
 (#set-pairs! @conceal conceal
   "\\overline{\\mathbf{A}}" "𝐀̅"
   "\\overline{\\mathbf{B}}" "𝐁̅"
   "\\overline{\\mathbf{C}}" "𝐂̅"
   "\\overline{\\mathbf{D}}" "𝐃̅"
   "\\overline{\\mathbf{E}}" "𝐄̅"
   "\\overline{\\mathbf{F}}" "𝐅̅"
   "\\overline{\\mathbf{G}}" "𝐆̅"
   "\\overline{\\mathbf{H}}" "𝐇̅"
   "\\overline{\\mathbf{I}}" "𝐈̅"
   "\\overline{\\mathbf{J}}" "𝐉̅"
   "\\overline{\\mathbf{K}}" "𝐊̅"
   "\\overline{\\mathbf{L}}" "𝐋̅"
   "\\overline{\\mathbf{M}}" "𝐌̅"
   "\\overline{\\mathbf{N}}" "𝐍̅"
   "\\overline{\\mathbf{O}}" "𝐎̅"
   "\\overline{\\mathbf{P}}" "𝐏̅"
   "\\overline{\\mathbf{Q}}" "𝐐̅"
   "\\overline{\\mathbf{R}}" "𝐑̅"
   "\\overline{\\mathbf{S}}" "𝐒̅"
   "\\overline{\\mathbf{T}}" "𝐓̅"
   "\\overline{\\mathbf{U}}" "𝐔̅"
   "\\overline{\\mathbf{V}}" "𝐕̅"
   "\\overline{\\mathbf{W}}" "𝐖̅"
   "\\overline{\\mathbf{X}}" "𝐗̅"
   "\\overline{\\mathbf{Y}}" "𝐘̅"
   "\\overline{\\mathbf{Z}}" "𝐙̅"
   "\\overline{\\mathbf{a}}" "𝐚̅"
   "\\overline{\\mathbf{b}}" "𝐛̅"
   "\\overline{\\mathbf{c}}" "𝐜̅"
   "\\overline{\\mathbf{d}}" "𝐝̅"
   "\\overline{\\mathbf{e}}" "𝐞̅"
   "\\overline{\\mathbf{f}}" "𝐟̅"
   "\\overline{\\mathbf{g}}" "𝐠̅"
   "\\overline{\\mathbf{h}}" "𝐡̅"
   "\\overline{\\mathbf{i}}" "𝐢̅"
   "\\overline{\\mathbf{j}}" "𝐣̅"
   "\\overline{\\mathbf{k}}" "𝐤̅"
   "\\overline{\\mathbf{l}}" "𝐥̅"
   "\\overline{\\mathbf{m}}" "𝐦̅"
   "\\overline{\\mathbf{n}}" "𝐧̅"
   "\\overline{\\mathbf{o}}" "𝐨̅"
   "\\overline{\\mathbf{p}}" "𝐩̅"
   "\\overline{\\mathbf{q}}" "𝐪̅"
   "\\overline{\\mathbf{r}}" "𝐫̅"
   "\\overline{\\mathbf{s}}" "𝐬̅"
   "\\overline{\\mathbf{t}}" "𝐭̅"
   "\\overline{\\mathbf{u}}" "𝐮̅"
   "\\overline{\\mathbf{v}}" "𝐯̅"
   "\\overline{\\mathbf{w}}" "𝐰̅"
   "\\overline{\\mathbf{x}}" "𝐱̅"
   "\\overline{\\mathbf{y}}" "𝐲̅"
   "\\overline{\\mathbf{z}}" "𝐳̅"))

((generic_command
   command: (command_name)
   arg: (curly_group)) @conceal
 (#lua-match? @conceal "\\overline{\\mathbb{[A-Z]}}")
 (#set! priority 101)
 (#set-pairs! @conceal conceal
   "\\overline{\\mathbb{A}}" "𝔸̅"
   "\\overline{\\mathbb{B}}" "𝔹̅"
   "\\overline{\\mathbb{C}}" "ℂ̅"
   "\\overline{\\mathbb{D}}" "𝔻̅"
   "\\overline{\\mathbb{E}}" "𝔼̅"
   "\\overline{\\mathbb{F}}" "𝔽̅"
   "\\overline{\\mathbb{G}}" "𝔾̅"
   "\\overline{\\mathbb{H}}" "ℍ̅"
   "\\overline{\\mathbb{I}}" "𝕀̅"
   "\\overline{\\mathbb{J}}" "𝕁̅"
   "\\overline{\\mathbb{K}}" "𝕂̅"
   "\\overline{\\mathbb{L}}" "𝕃̅"
   "\\overline{\\mathbb{M}}" "𝕄̅"
   "\\overline{\\mathbb{N}}" "ℕ̅"
   "\\overline{\\mathbb{O}}" "𝕆̅"
   "\\overline{\\mathbb{P}}" "ℙ̅"
   "\\overline{\\mathbb{Q}}" "ℚ̅"
   "\\overline{\\mathbb{R}}" "ℝ̅"
   "\\overline{\\mathbb{S}}" "𝕊̅"
   "\\overline{\\mathbb{T}}" "𝕋̅"
   "\\overline{\\mathbb{U}}" "𝕌̅"
   "\\overline{\\mathbb{V}}" "𝕍̅"
   "\\overline{\\mathbb{W}}" "𝕎̅"
   "\\overline{\\mathbb{X}}" "𝕏̅"
   "\\overline{\\mathbb{Y}}" "𝕐̅"
   "\\overline{\\mathbb{Z}}" "ℤ̅"))
