((generic_command
   command: (command_name)
   arg: (curly_group)) @conceal
 (#lua-match? @conceal "\\tilde{[a-zA-Z]}")
 (#set-pairs! @conceal conceal
  "\\tilde{a}" "ã"
  "\\tilde{b}" "b̃"
  "\\tilde{c}" "c̃"
  "\\tilde{d}" "d̃"
  "\\tilde{e}" "ẽ"
  "\\tilde{f}" "f̃"
  "\\tilde{g}" "g̃"
  "\\tilde{h}" "h̃"
  "\\tilde{i}" "ĩ"
  "\\tilde{j}" "j̃"
  "\\tilde{k}" "k̃"
  "\\tilde{l}" "l̃"
  "\\tilde{m}" "m̃"
  "\\tilde{n}" "ñ"
  "\\tilde{o}" "õ"
  "\\tilde{p}" "p̃"
  "\\tilde{q}" "q̃"
  "\\tilde{r}" "r̃"
  "\\tilde{s}" "s̃"
  "\\tilde{t}" "t̃"
  "\\tilde{u}" "ũ"
  "\\tilde{v}" "ṽ"
  "\\tilde{w}" "w̃"
  "\\tilde{x}" "x̃"
  "\\tilde{y}" "ỹ"
  "\\tilde{z}" "z̃"
  "\\tilde{A}" "Ã"
  "\\tilde{B}" "B̃"
  "\\tilde{C}" "C̃"
  "\\tilde{D}" "D̃"
  "\\tilde{E}" "Ẽ"
  "\\tilde{F}" "F̃"
  "\\tilde{G}" "G̃"
  "\\tilde{H}" "H̃"
  "\\tilde{I}" "Ĩ"
  "\\tilde{J}" "J̃"
  "\\tilde{K}" "K̃"
  "\\tilde{L}" "L̃"
  "\\tilde{M}" "M̃"
  "\\tilde{N}" "Ñ"
  "\\tilde{O}" "Õ"
  "\\tilde{P}" "P̃"
  "\\tilde{Q}" "Q̃"
  "\\tilde{R}" "R̃"
  "\\tilde{S}" "S̃"
  "\\tilde{T}" "T̃"
  "\\tilde{U}" "Ũ"
  "\\tilde{V}" "Ṽ"
  "\\tilde{W}" "W̃"
  "\\tilde{X}" "X̃"
  "\\tilde{Y}" "Ỹ"
  "\\tilde{Z}" "Z̃"))

((generic_command
   command: (command_name)
   arg: (curly_group)) @conceal
 (#lua-match? @conceal "\\tilde{\\[a-zA-Z]+}")
 (#set! priority 101)
 (#set-pairs! @conceal conceal
  ; Greek letters (lowercase) - using combining perispomeni (U+0342)
  "\\tilde{\\alpha}" "ᾶ"
  "\\tilde{\\beta}" "β͂"
  "\\tilde{\\gamma}" "γ͂"
  "\\tilde{\\delta}" "δ͂"
  "\\tilde{\\epsilon}" "ε͂"
  "\\tilde{\\zeta}" "ζ͂"
  "\\tilde{\\eta}" "ῆ"
  "\\tilde{\\theta}" "θ͂"
  "\\tilde{\\iota}" "ῖ"
  "\\tilde{\\kappa}" "κ͂"
  "\\tilde{\\lambda}" "λ͂"
  "\\tilde{\\mu}" "μ͂"
  "\\tilde{\\nu}" "ν͂"
  "\\tilde{\\xi}" "ξ͂"
  "\\tilde{\\omicron}" "ο͂"
  "\\tilde{\\pi}" "π͂"
  "\\tilde{\\rho}" "ρ͂"
  "\\tilde{\\sigma}" "σ͂"
  "\\tilde{\\tau}" "τ͂"
  "\\tilde{\\upsilon}" "ῦ"
  "\\tilde{\\phi}" "ϕ͂"
  "\\tilde{\\chi}" "χ͂"
  "\\tilde{\\psi}" "ψ͂"
  "\\tilde{\\omega}" "ῶ"
  
  ; Greek letters (uppercase)
  "\\tilde{\\Alpha}" "Α͂"
  "\\tilde{\\Beta}" "Β͂"
  "\\tilde{\\Gamma}" "Γ͂"
  "\\tilde{\\Delta}" "Δ͂"
  "\\tilde{\\Epsilon}" "Ε͂"
  "\\tilde{\\Zeta}" "Ζ͂"
  "\\tilde{\\Eta}" "Η͂"
  "\\tilde{\\Theta}" "Θ͂"
  "\\tilde{\\Iota}" "Ι͂"
  "\\tilde{\\Kappa}" "Κ͂"
  "\\tilde{\\Lambda}" "Λ͂"
  "\\tilde{\\Mu}" "Μ͂"
  "\\tilde{\\Nu}" "Ν͂"
  "\\tilde{\\Xi}" "Ξ͂"
  "\\tilde{\\Omicron}" "Ο͂"
  "\\tilde{\\Pi}" "Π͂"
  "\\tilde{\\Rho}" "Ρ͂"
  "\\tilde{\\Sigma}" "Σ͂"
  "\\tilde{\\Tau}" "Τ͂"
  "\\tilde{\\Upsilon}" "Υ͂"
  "\\tilde{\\Phi}" "Φ͂"
  "\\tilde{\\Chi}" "Χ͂"
  "\\tilde{\\Psi}" "Ψ͂"
  "\\tilde{\\Omega}" "Ω͂"
  
  ; Variants and alternate forms
  "\\tilde{\\varepsilon}" "ϵ͂"
  "\\tilde{\\vartheta}" "ϑ͂"
  "\\tilde{\\varpi}" "ϖ͂"
  "\\tilde{\\varrho}" "ϱ͂"
  "\\tilde{\\varsigma}" "ς͂"
  "\\tilde{\\varphi}" "φ͂"))

((generic_command
   command: (command_name)
   arg: (curly_group)) @conceal
 (#lua-match? @conceal "\\tilde{\\mathbf{[a-zA-Z]}}")
 (#set! priority 101)
 (#set-pairs! @conceal conceal
   "\\tilde{\\mathbf{A}}" "𝐀̃"
   "\\tilde{\\mathbf{B}}" "𝐁̃"
   "\\tilde{\\mathbf{C}}" "𝐂̃"
   "\\tilde{\\mathbf{D}}" "𝐃̃"
   "\\tilde{\\mathbf{E}}" "𝐄̃"
   "\\tilde{\\mathbf{F}}" "𝐅̃"
   "\\tilde{\\mathbf{G}}" "𝐆̃"
   "\\tilde{\\mathbf{H}}" "𝐇̃"
   "\\tilde{\\mathbf{I}}" "𝐈̃"
   "\\tilde{\\mathbf{J}}" "𝐉̃"
   "\\tilde{\\mathbf{K}}" "𝐊̃"
   "\\tilde{\\mathbf{L}}" "𝐋̃"
   "\\tilde{\\mathbf{M}}" "𝐌̃"
   "\\tilde{\\mathbf{N}}" "𝐍̃"
   "\\tilde{\\mathbf{O}}" "𝐎̃"
   "\\tilde{\\mathbf{P}}" "𝐏̃"
   "\\tilde{\\mathbf{Q}}" "𝐐̃"
   "\\tilde{\\mathbf{R}}" "𝐑̃"
   "\\tilde{\\mathbf{S}}" "𝐒̃"
   "\\tilde{\\mathbf{T}}" "𝐓̃"
   "\\tilde{\\mathbf{U}}" "𝐔̃"
   "\\tilde{\\mathbf{V}}" "𝐕̃"
   "\\tilde{\\mathbf{W}}" "𝐖̃"
   "\\tilde{\\mathbf{X}}" "𝐗̃"
   "\\tilde{\\mathbf{Y}}" "𝐘̃"
   "\\tilde{\\mathbf{Z}}" "𝐙̃"
   "\\tilde{\\mathbf{a}}" "𝐚̃"
   "\\tilde{\\mathbf{b}}" "𝐛̃"
   "\\tilde{\\mathbf{c}}" "𝐜̃"
   "\\tilde{\\mathbf{d}}" "𝐝̃"
   "\\tilde{\\mathbf{e}}" "𝐞̃"
   "\\tilde{\\mathbf{f}}" "𝐟̃"
   "\\tilde{\\mathbf{g}}" "𝐠̃"
   "\\tilde{\\mathbf{h}}" "𝐡̃"
   "\\tilde{\\mathbf{i}}" "𝐢̃"
   "\\tilde{\\mathbf{j}}" "𝐣̃"
   "\\tilde{\\mathbf{k}}" "𝐤̃"
   "\\tilde{\\mathbf{l}}" "𝐥̃"
   "\\tilde{\\mathbf{m}}" "𝐦̃"
   "\\tilde{\\mathbf{n}}" "𝐧̃"
   "\\tilde{\\mathbf{o}}" "𝐨̃"
   "\\tilde{\\mathbf{p}}" "𝐩̃"
   "\\tilde{\\mathbf{q}}" "𝐪̃"
   "\\tilde{\\mathbf{r}}" "𝐫̃"
   "\\tilde{\\mathbf{s}}" "𝐬̃"
   "\\tilde{\\mathbf{t}}" "𝐭̃"
   "\\tilde{\\mathbf{u}}" "𝐮̃"
   "\\tilde{\\mathbf{v}}" "𝐯̃"
   "\\tilde{\\mathbf{w}}" "𝐰̃"
   "\\tilde{\\mathbf{x}}" "𝐱̃"
   "\\tilde{\\mathbf{y}}" "𝐲̃"
   "\\tilde{\\mathbf{z}}" "𝐳̃"))

((generic_command
   command: (command_name)
   arg: (curly_group)) @conceal
 (#lua-match? @conceal "\\tilde{\\mathbb{[A-Z]}}")
 (#set! priority 101)
 (#set-pairs! @conceal conceal
   "\\tilde{\\mathbb{A}}" "𝔸̃"
   "\\tilde{\\mathbb{B}}" "𝔹̃"
   "\\tilde{\\mathbb{C}}" "ℂ̃"
   "\\tilde{\\mathbb{D}}" "𝔻̃"
   "\\tilde{\\mathbb{E}}" "𝔼̃"
   "\\tilde{\\mathbb{F}}" "𝔽̃"
   "\\tilde{\\mathbb{G}}" "𝔾̃"
   "\\tilde{\\mathbb{H}}" "ℍ̃"
   "\\tilde{\\mathbb{I}}" "𝕀̃"
   "\\tilde{\\mathbb{J}}" "𝕁̃"
   "\\tilde{\\mathbb{K}}" "𝕂̃"
   "\\tilde{\\mathbb{L}}" "𝕃̃"
   "\\tilde{\\mathbb{M}}" "𝕄̃"
   "\\tilde{\\mathbb{N}}" "ℕ̃"
   "\\tilde{\\mathbb{O}}" "𝕆̃"
   "\\tilde{\\mathbb{P}}" "ℙ̃"
   "\\tilde{\\mathbb{Q}}" "ℚ̃"
   "\\tilde{\\mathbb{R}}" "ℝ̃"
   "\\tilde{\\mathbb{S}}" "𝕊̃"
   "\\tilde{\\mathbb{T}}" "𝕋̃"
   "\\tilde{\\mathbb{U}}" "𝕌̃"
   "\\tilde{\\mathbb{V}}" "𝕍̃"
   "\\tilde{\\mathbb{W}}" "𝕎̃"
   "\\tilde{\\mathbb{X}}" "𝕏̃"
   "\\tilde{\\mathbb{Y}}" "𝕐̃"
   "\\tilde{\\mathbb{Z}}" "ℤ̃"))

((generic_command
   command: (command_name)
   arg: (curly_group)) @conceal
 (#lua-match? @conceal "\\widetilde{[a-zA-Z]}")
 (#set-pairs! @conceal conceal
  "\\widetilde{a}" "ã"
  "\\widetilde{b}" "b̃"
  "\\widetilde{c}" "c̃"
  "\\widetilde{d}" "d̃"
  "\\widetilde{e}" "ẽ"
  "\\widetilde{f}" "f̃"
  "\\widetilde{g}" "g̃"
  "\\widetilde{h}" "h̃"
  "\\widetilde{i}" "ĩ"
  "\\widetilde{j}" "j̃"
  "\\widetilde{k}" "k̃"
  "\\widetilde{l}" "l̃"
  "\\widetilde{m}" "m̃"
  "\\widetilde{n}" "ñ"
  "\\widetilde{o}" "õ"
  "\\widetilde{p}" "p̃"
  "\\widetilde{q}" "q̃"
  "\\widetilde{r}" "r̃"
  "\\widetilde{s}" "s̃"
  "\\widetilde{t}" "t̃"
  "\\widetilde{u}" "ũ"
  "\\widetilde{v}" "ṽ"
  "\\widetilde{w}" "w̃"
  "\\widetilde{x}" "x̃"
  "\\widetilde{y}" "ỹ"
  "\\widetilde{z}" "z̃"
  "\\widetilde{A}" "Ã"
  "\\widetilde{B}" "B̃"
  "\\widetilde{C}" "C̃"
  "\\widetilde{D}" "D̃"
  "\\widetilde{E}" "Ẽ"
  "\\widetilde{F}" "F̃"
  "\\widetilde{G}" "G̃"
  "\\widetilde{H}" "H̃"
  "\\widetilde{I}" "Ĩ"
  "\\widetilde{J}" "J̃"
  "\\widetilde{K}" "K̃"
  "\\widetilde{L}" "L̃"
  "\\widetilde{M}" "M̃"
  "\\widetilde{N}" "Ñ"
  "\\widetilde{O}" "Õ"
  "\\widetilde{P}" "P̃"
  "\\widetilde{Q}" "Q̃"
  "\\widetilde{R}" "R̃"
  "\\widetilde{S}" "S̃"
  "\\widetilde{T}" "T̃"
  "\\widetilde{U}" "Ũ"
  "\\widetilde{V}" "Ṽ"
  "\\widetilde{W}" "W̃"
  "\\widetilde{X}" "X̃"
  "\\widetilde{Y}" "Ỹ"
  "\\widetilde{Z}" "Z̃"))

((generic_command
   command: (command_name)
   arg: (curly_group)) @conceal
 (#lua-match? @conceal "\\widetilde{\\[a-zA-Z]+}")
 (#set! priority 101)
 (#set-pairs! @conceal conceal
  ; Greek letters (lowercase) - using combining perispomeni (U+0342)
  "\\widetilde{\\alpha}" "ᾶ"
  "\\widetilde{\\beta}" "β͂"
  "\\widetilde{\\gamma}" "γ͂"
  "\\widetilde{\\delta}" "δ͂"
  "\\widetilde{\\epsilon}" "ε͂"
  "\\widetilde{\\zeta}" "ζ͂"
  "\\widetilde{\\eta}" "ῆ"
  "\\widetilde{\\theta}" "θ͂"
  "\\widetilde{\\iota}" "ῖ"
  "\\widetilde{\\kappa}" "κ͂"
  "\\widetilde{\\lambda}" "λ͂"
  "\\widetilde{\\mu}" "μ͂"
  "\\widetilde{\\nu}" "ν͂"
  "\\widetilde{\\xi}" "ξ͂"
  "\\widetilde{\\omicron}" "ο͂"
  "\\widetilde{\\pi}" "π͂"
  "\\widetilde{\\rho}" "ρ͂"
  "\\widetilde{\\sigma}" "σ͂"
  "\\widetilde{\\tau}" "τ͂"
  "\\widetilde{\\upsilon}" "ῦ"
  "\\widetilde{\\phi}" "ϕ͂"
  "\\widetilde{\\chi}" "χ͂"
  "\\widetilde{\\psi}" "ψ͂"
  "\\widetilde{\\omega}" "ῶ"
  
  ; Greek letters (uppercase)
  "\\widetilde{\\Alpha}" "Α͂"
  "\\widetilde{\\Beta}" "Β͂"
  "\\widetilde{\\Gamma}" "Γ͂"
  "\\widetilde{\\Delta}" "Δ͂"
  "\\widetilde{\\Epsilon}" "Ε͂"
  "\\widetilde{\\Zeta}" "Ζ͂"
  "\\widetilde{\\Eta}" "Η͂"
  "\\widetilde{\\Theta}" "Θ͂"
  "\\widetilde{\\Iota}" "Ι͂"
  "\\widetilde{\\Kappa}" "Κ͂"
  "\\widetilde{\\Lambda}" "Λ͂"
  "\\widetilde{\\Mu}" "Μ͂"
  "\\widetilde{\\Nu}" "Ν͂"
  "\\widetilde{\\Xi}" "Ξ͂"
  "\\widetilde{\\Omicron}" "Ο͂"
  "\\widetilde{\\Pi}" "Π͂"
  "\\widetilde{\\Rho}" "Ρ͂"
  "\\widetilde{\\Sigma}" "Σ͂"
  "\\widetilde{\\Tau}" "Τ͂"
  "\\widetilde{\\Upsilon}" "Υ͂"
  "\\widetilde{\\Phi}" "Φ͂"
  "\\widetilde{\\Chi}" "Χ͂"
  "\\widetilde{\\Psi}" "Ψ͂"
  "\\widetilde{\\Omega}" "Ω͂"
  
  ; Variants and alternate forms
  "\\widetilde{\\varepsilon}" "ϵ͂"
  "\\widetilde{\\vartheta}" "ϑ͂"
  "\\widetilde{\\varpi}" "ϖ͂"
  "\\widetilde{\\varrho}" "ϱ͂"
  "\\widetilde{\\varsigma}" "ς͂"
  "\\widetilde{\\varphi}" "φ͂"))

((generic_command
   command: (command_name)
   arg: (curly_group)) @conceal
 (#lua-match? @conceal "\\widetilde{\\mathbf{[a-zA-Z]}}")
 (#set! priority 101)
 (#set-pairs! @conceal conceal
   "\\widetilde{\\mathbf{A}}" "𝐀̃"
   "\\widetilde{\\mathbf{B}}" "𝐁̃"
   "\\widetilde{\\mathbf{C}}" "𝐂̃"
   "\\widetilde{\\mathbf{D}}" "𝐃̃"
   "\\widetilde{\\mathbf{E}}" "𝐄̃"
   "\\widetilde{\\mathbf{F}}" "𝐅̃"
   "\\widetilde{\\mathbf{G}}" "𝐆̃"
   "\\widetilde{\\mathbf{H}}" "𝐇̃"
   "\\widetilde{\\mathbf{I}}" "𝐈̃"
   "\\widetilde{\\mathbf{J}}" "𝐉̃"
   "\\widetilde{\\mathbf{K}}" "𝐊̃"
   "\\widetilde{\\mathbf{L}}" "𝐋̃"
   "\\widetilde{\\mathbf{M}}" "𝐌̃"
   "\\widetilde{\\mathbf{N}}" "𝐍̃"
   "\\widetilde{\\mathbf{O}}" "𝐎̃"
   "\\widetilde{\\mathbf{P}}" "𝐏̃"
   "\\widetilde{\\mathbf{Q}}" "𝐐̃"
   "\\widetilde{\\mathbf{R}}" "𝐑̃"
   "\\widetilde{\\mathbf{S}}" "𝐒̃"
   "\\widetilde{\\mathbf{T}}" "𝐓̃"
   "\\widetilde{\\mathbf{U}}" "𝐔̃"
   "\\widetilde{\\mathbf{V}}" "𝐕̃"
   "\\widetilde{\\mathbf{W}}" "𝐖̃"
   "\\widetilde{\\mathbf{X}}" "𝐗̃"
   "\\widetilde{\\mathbf{Y}}" "𝐘̃"
   "\\widetilde{\\mathbf{Z}}" "𝐙̃"
   "\\widetilde{\\mathbf{a}}" "𝐚̃"
   "\\widetilde{\\mathbf{b}}" "𝐛̃"
   "\\widetilde{\\mathbf{c}}" "𝐜̃"
   "\\widetilde{\\mathbf{d}}" "𝐝̃"
   "\\widetilde{\\mathbf{e}}" "𝐞̃"
   "\\widetilde{\\mathbf{f}}" "𝐟̃"
   "\\widetilde{\\mathbf{g}}" "𝐠̃"
   "\\widetilde{\\mathbf{h}}" "𝐡̃"
   "\\widetilde{\\mathbf{i}}" "𝐢̃"
   "\\widetilde{\\mathbf{j}}" "𝐣̃"
   "\\widetilde{\\mathbf{k}}" "𝐤̃"
   "\\widetilde{\\mathbf{l}}" "𝐥̃"
   "\\widetilde{\\mathbf{m}}" "𝐦̃"
   "\\widetilde{\\mathbf{n}}" "𝐧̃"
   "\\widetilde{\\mathbf{o}}" "𝐨̃"
   "\\widetilde{\\mathbf{p}}" "𝐩̃"
   "\\widetilde{\\mathbf{q}}" "𝐪̃"
   "\\widetilde{\\mathbf{r}}" "𝐫̃"
   "\\widetilde{\\mathbf{s}}" "𝐬̃"
   "\\widetilde{\\mathbf{t}}" "𝐭̃"
   "\\widetilde{\\mathbf{u}}" "𝐮̃"
   "\\widetilde{\\mathbf{v}}" "𝐯̃"
   "\\widetilde{\\mathbf{w}}" "𝐰̃"
   "\\widetilde{\\mathbf{x}}" "𝐱̃"
   "\\widetilde{\\mathbf{y}}" "𝐲̃"
   "\\widetilde{\\mathbf{z}}" "𝐳̃"))

((generic_command
   command: (command_name)
   arg: (curly_group)) @conceal
 (#lua-match? @conceal "\\widetilde{\\mathbb{[A-Z]}}")
 (#set! priority 101)
 (#set-pairs! @conceal conceal
   "\\widetilde{\\mathbb{A}}" "𝔸̃"
   "\\widetilde{\\mathbb{B}}" "𝔹̃"
   "\\widetilde{\\mathbb{C}}" "ℂ̃"
   "\\widetilde{\\mathbb{D}}" "𝔻̃"
   "\\widetilde{\\mathbb{E}}" "𝔼̃"
   "\\widetilde{\\mathbb{F}}" "𝔽̃"
   "\\widetilde{\\mathbb{G}}" "𝔾̃"
   "\\widetilde{\\mathbb{H}}" "ℍ̃"
   "\\widetilde{\\mathbb{I}}" "𝕀̃"
   "\\widetilde{\\mathbb{J}}" "𝕁̃"
   "\\widetilde{\\mathbb{K}}" "𝕂̃"
   "\\widetilde{\\mathbb{L}}" "𝕃̃"
   "\\widetilde{\\mathbb{M}}" "𝕄̃"
   "\\widetilde{\\mathbb{N}}" "ℕ̃"
   "\\widetilde{\\mathbb{O}}" "𝕆̃"
   "\\widetilde{\\mathbb{P}}" "ℙ̃"
   "\\widetilde{\\mathbb{Q}}" "ℚ̃"
   "\\widetilde{\\mathbb{R}}" "ℝ̃"
   "\\widetilde{\\mathbb{S}}" "𝕊̃"
   "\\widetilde{\\mathbb{T}}" "𝕋̃"
   "\\widetilde{\\mathbb{U}}" "𝕌̃"
   "\\widetilde{\\mathbb{V}}" "𝕍̃"
   "\\widetilde{\\mathbb{W}}" "𝕎̃"
   "\\widetilde{\\mathbb{X}}" "𝕏̃"
   "\\widetilde{\\mathbb{Y}}" "𝕐̃"
   "\\widetilde{\\mathbb{Z}}" "ℤ̃"))
