((generic_command
   command: (command_name)
   arg: (curly_group)) @conceal
 (#lua-match? @conceal "\\hat{[a-zA-Z]}")
 (#set-pairs! @conceal conceal
  "\\hat{a}" "â"
  "\\hat{b}" "b̂"
  "\\hat{c}" "ĉ"
  "\\hat{d}" "d̂"
  "\\hat{e}" "ê"
  "\\hat{f}" "f̂"
  "\\hat{g}" "ĝ"
  "\\hat{h}" "ĥ"
  "\\hat{i}" "î"
  "\\hat{j}" "ĵ"
  "\\hat{k}" "k̂"
  "\\hat{l}" "l̂"
  "\\hat{m}" "m̂"
  "\\hat{n}" "n̂"
  "\\hat{o}" "ô"
  "\\hat{p}" "p̂"
  "\\hat{q}" "q̂"
  "\\hat{r}" "r̂"
  "\\hat{s}" "ŝ"
  "\\hat{t}" "t̂"
  "\\hat{u}" "û"
  "\\hat{v}" "v̂"
  "\\hat{w}" "ŵ"
  "\\hat{x}" "x̂"
  "\\hat{y}" "ŷ"
  "\\hat{z}" "ẑ"
  "\\hat{A}" "Â"
  "\\hat{B}" "B̂"
  "\\hat{C}" "Ĉ"
  "\\hat{D}" "D̂"
  "\\hat{E}" "Ê"
  "\\hat{F}" "F̂"
  "\\hat{G}" "Ĝ"
  "\\hat{H}" "Ĥ"
  "\\hat{I}" "Î"
  "\\hat{J}" "Ĵ"
  "\\hat{K}" "K̂"
  "\\hat{L}" "L̂"
  "\\hat{M}" "M̂"
  "\\hat{N}" "N̂"
  "\\hat{O}" "Ô"
  "\\hat{P}" "P̂"
  "\\hat{Q}" "Q̂"
  "\\hat{R}" "R̂"
  "\\hat{S}" "Ŝ"
  "\\hat{T}" "T̂"
  "\\hat{U}" "Û"
  "\\hat{V}" "V̂"
  "\\hat{W}" "Ŵ"
  "\\hat{X}" "X̂"
  "\\hat{Y}" "Ŷ"
  "\\hat{Z}" "Ẑ"))

((generic_command
   command: (command_name)
   arg: (curly_group)) @conceal
 (#lua-match? @conceal "\\hat{\\[a-zA-Z]+}")
 (#set! priority 101)
 (#set-pairs! @conceal conceal
  ; Greek letters (lowercase)
  "\\hat{\\alpha}" "α̂"
  "\\hat{\\beta}" "β̂"
  "\\hat{\\gamma}" "γ̂"
  "\\hat{\\delta}" "δ̂"
  "\\hat{\\epsilon}" "ε̂"
  "\\hat{\\zeta}" "ζ̂"
  "\\hat{\\eta}" "η̂"
  "\\hat{\\theta}" "θ̂"
  "\\hat{\\iota}" "ι̂"
  "\\hat{\\kappa}" "κ̂"
  "\\hat{\\lambda}" "λ̂"
  "\\hat{\\mu}" "μ̂"
  "\\hat{\\nu}" "ν̂"
  "\\hat{\\xi}" "ξ̂"
  "\\hat{\\omicron}" "ο̂"
  "\\hat{\\pi}" "π̂"
  "\\hat{\\rho}" "ρ̂"
  "\\hat{\\sigma}" "σ̂"
  "\\hat{\\tau}" "τ̂"
  "\\hat{\\upsilon}" "υ̂"
  "\\hat{\\phi}" "ϕ̂"
  "\\hat{\\chi}" "χ̂"
  "\\hat{\\psi}" "ψ̂"
  "\\hat{\\omega}" "ω̂"
  
  ; Greek letters (uppercase)
  "\\hat{\\Alpha}" "Α̂"
  "\\hat{\\Beta}" "Β̂"
  "\\hat{\\Gamma}" "Γ̂"
  "\\hat{\\Delta}" "Δ̂"
  "\\hat{\\Epsilon}" "Ε̂"
  "\\hat{\\Zeta}" "Ζ̂"
  "\\hat{\\Eta}" "Η̂"
  "\\hat{\\Theta}" "Θ̂"
  "\\hat{\\Iota}" "Ι̂"
  "\\hat{\\Kappa}" "Κ̂"
  "\\hat{\\Lambda}" "Λ̂"
  "\\hat{\\Mu}" "Μ̂"
  "\\hat{\\Nu}" "Ν̂"
  "\\hat{\\Xi}" "Ξ̂"
  "\\hat{\\Omicron}" "Ο̂"
  "\\hat{\\Pi}" "Π̂"
  "\\hat{\\Rho}" "Ρ̂"
  "\\hat{\\Sigma}" "Σ̂"
  "\\hat{\\Tau}" "Τ̂"
  "\\hat{\\Upsilon}" "Υ̂"
  "\\hat{\\Phi}" "Φ̂"
  "\\hat{\\Chi}" "Χ̂"
  "\\hat{\\Psi}" "Ψ̂"
  "\\hat{\\Omega}" "Ω̂"
  
  ; Variants and alternate forms
  "\\hat{\\varepsilon}" "ϵ̂"
  "\\hat{\\vartheta}" "ϑ̂"
  "\\hat{\\varpi}" "ϖ̂"
  "\\hat{\\varrho}" "ϱ̂"
  "\\hat{\\varsigma}" "ς̂"
  "\\hat{\\varphi}" "φ̂"))

((generic_command
   command: (command_name)
   arg: (curly_group)) @conceal
 (#lua-match? @conceal "\\widehat{[a-zA-Z]}")
 (#set-pairs! @conceal conceal
  "\\widehat{a}" "â"
  "\\widehat{b}" "b̂"
  "\\widehat{c}" "ĉ"
  "\\widehat{d}" "d̂"
  "\\widehat{e}" "ê"
  "\\widehat{f}" "f̂"
  "\\widehat{g}" "ĝ"
  "\\widehat{h}" "ĥ"
  "\\widehat{i}" "î"
  "\\widehat{j}" "ĵ"
  "\\widehat{k}" "k̂"
  "\\widehat{l}" "l̂"
  "\\widehat{m}" "m̂"
  "\\widehat{n}" "n̂"
  "\\widehat{o}" "ô"
  "\\widehat{p}" "p̂"
  "\\widehat{q}" "q̂"
  "\\widehat{r}" "r̂"
  "\\widehat{s}" "ŝ"
  "\\widehat{t}" "t̂"
  "\\widehat{u}" "û"
  "\\widehat{v}" "v̂"
  "\\widehat{w}" "ŵ"
  "\\widehat{x}" "x̂"
  "\\widehat{y}" "ŷ"
  "\\widehat{z}" "ẑ"
  "\\widehat{A}" "Â"
  "\\widehat{B}" "B̂"
  "\\widehat{C}" "Ĉ"
  "\\widehat{D}" "D̂"
  "\\widehat{E}" "Ê"
  "\\widehat{F}" "F̂"
  "\\widehat{G}" "Ĝ"
  "\\widehat{H}" "Ĥ"
  "\\widehat{I}" "Î"
  "\\widehat{J}" "Ĵ"
  "\\widehat{K}" "K̂"
  "\\widehat{L}" "L̂"
  "\\widehat{M}" "M̂"
  "\\widehat{N}" "N̂"
  "\\widehat{O}" "Ô"
  "\\widehat{P}" "P̂"
  "\\widehat{Q}" "Q̂"
  "\\widehat{R}" "R̂"
  "\\widehat{S}" "Ŝ"
  "\\widehat{T}" "T̂"
  "\\widehat{U}" "Û"
  "\\widehat{V}" "V̂"
  "\\widehat{W}" "Ŵ"
  "\\widehat{X}" "X̂"
  "\\widehat{Y}" "Ŷ"
  "\\widehat{Z}" "Ẑ"))

((generic_command
   command: (command_name)
   arg: (curly_group)) @conceal
 (#lua-match? @conceal "\\widehat{\\[a-zA-Z]+}")
 (#set! priority 101)
 (#set-pairs! @conceal conceal
  ; Greek letters (lowercase)
  "\\widehat{\\alpha}" "α̂"
  "\\widehat{\\beta}" "β̂"
  "\\widehat{\\gamma}" "γ̂"
  "\\widehat{\\delta}" "δ̂"
  "\\widehat{\\epsilon}" "ε̂"
  "\\widehat{\\zeta}" "ζ̂"
  "\\widehat{\\eta}" "η̂"
  "\\widehat{\\theta}" "θ̂"
  "\\widehat{\\iota}" "ι̂"
  "\\widehat{\\kappa}" "κ̂"
  "\\widehat{\\lambda}" "λ̂"
  "\\widehat{\\mu}" "μ̂"
  "\\widehat{\\nu}" "ν̂"
  "\\widehat{\\xi}" "ξ̂"
  "\\widehat{\\omicron}" "ο̂"
  "\\widehat{\\pi}" "π̂"
  "\\widehat{\\rho}" "ρ̂"
  "\\widehat{\\sigma}" "σ̂"
  "\\widehat{\\tau}" "τ̂"
  "\\widehat{\\upsilon}" "υ̂"
  "\\widehat{\\phi}" "ϕ̂"
  "\\widehat{\\chi}" "χ̂"
  "\\widehat{\\psi}" "ψ̂"
  "\\widehat{\\omega}" "ω̂"
  
  ; Greek letters (uppercase)
  "\\widehat{\\Alpha}" "Α̂"
  "\\widehat{\\Beta}" "Β̂"
  "\\widehat{\\Gamma}" "Γ̂"
  "\\widehat{\\Delta}" "Δ̂"
  "\\widehat{\\Epsilon}" "Ε̂"
  "\\widehat{\\Zeta}" "Ζ̂"
  "\\widehat{\\Eta}" "Η̂"
  "\\widehat{\\Theta}" "Θ̂"
  "\\widehat{\\Iota}" "Ι̂"
  "\\widehat{\\Kappa}" "Κ̂"
  "\\widehat{\\Lambda}" "Λ̂"
  "\\widehat{\\Mu}" "Μ̂"
  "\\widehat{\\Nu}" "Ν̂"
  "\\widehat{\\Xi}" "Ξ̂"
  "\\widehat{\\Omicron}" "Ο̂"
  "\\widehat{\\Pi}" "Π̂"
  "\\widehat{\\Rho}" "Ρ̂"
  "\\widehat{\\Sigma}" "Σ̂"
  "\\widehat{\\Tau}" "Τ̂"
  "\\widehat{\\Upsilon}" "Υ̂"
  "\\widehat{\\Phi}" "Φ̂"
  "\\widehat{\\Chi}" "Χ̂"
  "\\widehat{\\Psi}" "Ψ̂"
  "\\widehat{\\Omega}" "Ω̂"
  
  ; Variants and alternate forms
  "\\widehat{\\varepsilon}" "ϵ̂"
  "\\widehat{\\vartheta}" "ϑ̂"
  "\\widehat{\\varpi}" "ϖ̂"
  "\\widehat{\\varrho}" "ϱ̂"
  "\\widehat{\\varsigma}" "ς̂"
  "\\widehat{\\varphi}" "φ̂"))
