((generic_command
   command: (command_name)
   arg: (curly_group)) @conceal
 (#lua-match? @conceal "\\vec{[a-zA-Z]}")
 (#set-pairs! @conceal conceal
  "\\vec{a}" "a⃗"
  "\\vec{b}" "b⃗"
  "\\vec{c}" "c⃗"
  "\\vec{d}" "d⃗"
  "\\vec{e}" "e⃗"
  "\\vec{f}" "f⃗"
  "\\vec{g}" "g⃗"
  "\\vec{h}" "h⃗"
  "\\vec{i}" "i⃗"
  "\\vec{j}" "j⃗"
  "\\vec{k}" "k⃗"
  "\\vec{l}" "l⃗"
  "\\vec{m}" "m⃗"
  "\\vec{n}" "n⃗"
  "\\vec{o}" "o⃗"
  "\\vec{p}" "p⃗"
  "\\vec{q}" "q⃗"
  "\\vec{r}" "r⃗"
  "\\vec{s}" "s⃗"
  "\\vec{t}" "t⃗"
  "\\vec{u}" "u⃗"
  "\\vec{v}" "v⃗"
  "\\vec{w}" "w⃗"
  "\\vec{x}" "x⃗"
  "\\vec{y}" "y⃗"
  "\\vec{z}" "z⃗"
  "\\vec{A}" "A⃗"
  "\\vec{B}" "B⃗"
  "\\vec{C}" "C⃗"
  "\\vec{D}" "D⃗"
  "\\vec{E}" "E⃗"
  "\\vec{F}" "F⃗"
  "\\vec{G}" "G⃗"
  "\\vec{H}" "H⃗"
  "\\vec{I}" "I⃗"
  "\\vec{J}" "J⃗"
  "\\vec{K}" "K⃗"
  "\\vec{L}" "L⃗"
  "\\vec{M}" "M⃗"
  "\\vec{N}" "N⃗"
  "\\vec{O}" "O⃗"
  "\\vec{P}" "P⃗"
  "\\vec{Q}" "Q⃗"
  "\\vec{R}" "R⃗"
  "\\vec{S}" "S⃗"
  "\\vec{T}" "T⃗"
  "\\vec{U}" "U⃗"
  "\\vec{V}" "V⃗"
  "\\vec{W}" "W⃗"
  "\\vec{X}" "X⃗"
  "\\vec{Y}" "Y⃗"
  "\\vec{Z}" "Z⃗"))

((generic_command
   command: (command_name)
   arg: (curly_group)) @conceal
 (#lua-match? @conceal "\\vec{[a-zA-Z]}")
 (#set! priority 101)
 (#set-pairs! @conceal conceal
  ; Lowercase Greek letters
  "\\vec{\\alpha}" "α⃗"
  "\\vec{\\beta}" "β⃗"
  "\\vec{\\gamma}" "γ⃗"
  "\\vec{\\delta}" "δ⃗"
  "\\vec{\\epsilon}" "ε⃗"
  "\\vec{\\zeta}" "ζ⃗"
  "\\vec{\\eta}" "η⃗"
  "\\vec{\\theta}" "θ⃗"
  "\\vec{\\iota}" "ι⃗"
  "\\vec{\\kappa}" "κ⃗"
  "\\vec{\\lambda}" "λ⃗"
  "\\vec{\\mu}" "μ⃗"
  "\\vec{\\nu}" "ν⃗"
  "\\vec{\\xi}" "ξ⃗"
  "\\vec{\\omicron}" "ο⃗"
  "\\vec{\\pi}" "π⃗"
  "\\vec{\\rho}" "ρ⃗"
  "\\vec{\\sigma}" "σ⃗"
  "\\vec{\\tau}" "τ⃗"
  "\\vec{\\upsilon}" "υ⃗"
  "\\vec{\\phi}" "ϕ⃗"
  "\\vec{\\chi}" "χ⃗"
  "\\vec{\\psi}" "ψ⃗"
  "\\vec{\\omega}" "ω⃗"
  
  ; Uppercase Greek letters
  "\\vec{\\Alpha}" "Α⃗"
  "\\vec{\\Beta}" "Β⃗"
  "\\vec{\\Gamma}" "Γ⃗"
  "\\vec{\\Delta}" "Δ⃗"
  "\\vec{\\Epsilon}" "Ε⃗"
  "\\vec{\\Zeta}" "Ζ⃗"
  "\\vec{\\Eta}" "Η⃗"
  "\\vec{\\Theta}" "Θ⃗"
  "\\vec{\\Iota}" "Ι⃗"
  "\\vec{\\Kappa}" "Κ⃗"
  "\\vec{\\Lambda}" "Λ⃗"
  "\\vec{\\Mu}" "Μ⃗"
  "\\vec{\\Nu}" "Ν⃗"
  "\\vec{\\Xi}" "Ξ⃗"
  "\\vec{\\Omicron}" "Ο⃗"
  "\\vec{\\Pi}" "Π⃗"
  "\\vec{\\Rho}" "Ρ⃗"
  "\\vec{\\Sigma}" "Σ⃗"
  "\\vec{\\Tau}" "Τ⃗"
  "\\vec{\\Upsilon}" "Υ⃗"
  "\\vec{\\Phi}" "Φ⃗"
  "\\vec{\\Chi}" "Χ⃗"
  "\\vec{\\Psi}" "Ψ⃗"
  "\\vec{\\Omega}" "Ω⃗"
  
  ; Variants and alternate forms
  "\\vec{\\varepsilon}" "ϵ⃗"
  "\\vec{\\vartheta}" "ϑ⃗"
  "\\vec{\\varpi}" "ϖ⃗"
  "\\vec{\\varrho}" "ϱ⃗"
  "\\vec{\\varsigma}" "ς⃗"
  "\\vec{\\varphi}" "φ⃗"))

((generic_command
   command: (command_name)
   arg: (curly_group)) @conceal
 (#lua-match? @conceal "\\vec{\\mathbf{[a-zA-Z]}}")
 (#set! priority 101)
 (#set-pairs! @conceal conceal
   "\\vec{\\mathbf{A}}" "𝐀⃗"
   "\\vec{\\mathbf{B}}" "𝐁⃗"
   "\\vec{\\mathbf{C}}" "𝐂⃗"
   "\\vec{\\mathbf{D}}" "𝐃⃗"
   "\\vec{\\mathbf{E}}" "𝐄⃗"
   "\\vec{\\mathbf{F}}" "𝐅⃗"
   "\\vec{\\mathbf{G}}" "𝐆⃗"
   "\\vec{\\mathbf{H}}" "𝐇⃗"
   "\\vec{\\mathbf{I}}" "𝐈⃗"
   "\\vec{\\mathbf{J}}" "𝐉⃗"
   "\\vec{\\mathbf{K}}" "𝐊⃗"
   "\\vec{\\mathbf{L}}" "𝐋⃗"
   "\\vec{\\mathbf{M}}" "𝐌⃗"
   "\\vec{\\mathbf{N}}" "𝐍⃗"
   "\\vec{\\mathbf{O}}" "𝐎⃗"
   "\\vec{\\mathbf{P}}" "𝐏⃗"
   "\\vec{\\mathbf{Q}}" "𝐐⃗"
   "\\vec{\\mathbf{R}}" "𝐑⃗"
   "\\vec{\\mathbf{S}}" "𝐒⃗"
   "\\vec{\\mathbf{T}}" "𝐓⃗"
   "\\vec{\\mathbf{U}}" "𝐔⃗"
   "\\vec{\\mathbf{V}}" "𝐕⃗"
   "\\vec{\\mathbf{W}}" "𝐖⃗"
   "\\vec{\\mathbf{X}}" "𝐗⃗"
   "\\vec{\\mathbf{Y}}" "𝐘⃗"
   "\\vec{\\mathbf{Z}}" "𝐙⃗"
   "\\vec{\\mathbf{a}}" "𝐚⃗"
   "\\vec{\\mathbf{b}}" "𝐛⃗"
   "\\vec{\\mathbf{c}}" "𝐜⃗"
   "\\vec{\\mathbf{d}}" "𝐝⃗"
   "\\vec{\\mathbf{e}}" "𝐞⃗"
   "\\vec{\\mathbf{f}}" "𝐟⃗"
   "\\vec{\\mathbf{g}}" "𝐠⃗"
   "\\vec{\\mathbf{h}}" "𝐡⃗"
   "\\vec{\\mathbf{i}}" "𝐢⃗"
   "\\vec{\\mathbf{j}}" "𝐣⃗"
   "\\vec{\\mathbf{k}}" "𝐤⃗"
   "\\vec{\\mathbf{l}}" "𝐥⃗"
   "\\vec{\\mathbf{m}}" "𝐦⃗"
   "\\vec{\\mathbf{n}}" "𝐧⃗"
   "\\vec{\\mathbf{o}}" "𝐨⃗"
   "\\vec{\\mathbf{p}}" "𝐩⃗"
   "\\vec{\\mathbf{q}}" "𝐪⃗"
   "\\vec{\\mathbf{r}}" "𝐫⃗"
   "\\vec{\\mathbf{s}}" "𝐬⃗"
   "\\vec{\\mathbf{t}}" "𝐭⃗"
   "\\vec{\\mathbf{u}}" "𝐮⃗"
   "\\vec{\\mathbf{v}}" "𝐯⃗"
   "\\vec{\\mathbf{w}}" "𝐰⃗"
   "\\vec{\\mathbf{x}}" "𝐱⃗"
   "\\vec{\\mathbf{y}}" "𝐲⃗"
   "\\vec{\\mathbf{z}}" "𝐳⃗"))
