((generic_command
   command: (command_name)
   arg: (curly_group)) @conceal
 (#lua-match? @conceal "\\hat{[a-zA-Z]}")
 (#set-pairs! @conceal conceal
  "\\hat{a}" "â"
  "\\hat{b}" "b̂"
  "\\hat{c}" "ĉ"
  "\\hat{d}" "d̂"
  "\\hat{e}" "ê"
  "\\hat{f}" "f̂"
  "\\hat{g}" "ĝ"
  "\\hat{h}" "ĥ"
  "\\hat{i}" "î"
  "\\hat{j}" "ĵ"
  "\\hat{k}" "k̂"
  "\\hat{l}" "l̂"
  "\\hat{m}" "m̂"
  "\\hat{n}" "n̂"
  "\\hat{o}" "ô"
  "\\hat{p}" "p̂"
  "\\hat{q}" "q̂"
  "\\hat{r}" "r̂"
  "\\hat{s}" "ŝ"
  "\\hat{t}" "t̂"
  "\\hat{u}" "û"
  "\\hat{v}" "v̂"
  "\\hat{w}" "ŵ"
  "\\hat{x}" "x̂"
  "\\hat{y}" "ŷ"
  "\\hat{z}" "ẑ"
  "\\hat{A}" "Â"
  "\\hat{B}" "B̂"
  "\\hat{C}" "Ĉ"
  "\\hat{D}" "D̂"
  "\\hat{E}" "Ê"
  "\\hat{F}" "F̂"
  "\\hat{G}" "Ĝ"
  "\\hat{H}" "Ĥ"
  "\\hat{I}" "Î"
  "\\hat{J}" "Ĵ"
  "\\hat{K}" "K̂"
  "\\hat{L}" "L̂"
  "\\hat{M}" "M̂"
  "\\hat{N}" "N̂"
  "\\hat{O}" "Ô"
  "\\hat{P}" "P̂"
  "\\hat{Q}" "Q̂"
  "\\hat{R}" "R̂"
  "\\hat{S}" "Ŝ"
  "\\hat{T}" "T̂"
  "\\hat{U}" "Û"
  "\\hat{V}" "V̂"
  "\\hat{W}" "Ŵ"
  "\\hat{X}" "X̂"
  "\\hat{Y}" "Ŷ"
  "\\hat{Z}" "Ẑ"))

; ((generic_command
;    command: (command_name)
;    arg: (curly_group)) @conceal
;  (#lua-match? @conceal "\\hat{\\[a-zA-Z]+}")
;  (#set! priority 101)
;  (#set-pairs! @conceal conceal
;   ; Greek letters (lowercase)
;   "\\hat{\\alpha}" "α͆"
;   "\\hat{\\beta}" "β͆"
;   "\\hat{\\gamma}" "γ͆"
;   "\\hat{\\delta}" "δ͆"
;   "\\hat{\\epsilon}" "ε͆"
;   "\\hat{\\zeta}" "ζ͆"
;   "\\hat{\\eta}" "η͆"
;   "\\hat{\\theta}" "θ͆"
;   "\\hat{\\iota}" "ι͆"
;   "\\hat{\\kappa}" "κ͆"
;   "\\hat{\\lambda}" "λ͆"
;   "\\hat{\\mu}" "μ͆"
;   "\\hat{\\nu}" "ν͆"
;   "\\hat{\\xi}" "ξ͆"
;   "\\hat{\\omicron}" "ο͆"
;   "\\hat{\\pi}" "π͆"
;   "\\hat{\\rho}" "ρ͆"
;   "\\hat{\\sigma}" "σ͆"
;   "\\hat{\\tau}" "τ͆"
;   "\\hat{\\upsilon}" "υ͆"
;   "\\hat{\\phi}" "ϕ͆"
;   "\\hat{\\chi}" "χ͆"
;   "\\hat{\\psi}" "ψ͆"
;   "\\hat{\\omega}" "ω͆"
;
;   ; Greek letters (uppercase)
;   "\\hat{\\Alpha}" "Α͆"
;   "\\hat{\\Beta}" "Β͆"
;   "\\hat{\\Gamma}" "Γ͆"
;   "\\hat{\\Delta}" "Δ͆"
;   "\\hat{\\Epsilon}" "Ε͆"
;   "\\hat{\\Zeta}" "Ζ͆"
;   "\\hat{\\Eta}" "Η͆"
;   "\\hat{\\Theta}" "Θ͆"
;   "\\hat{\\Iota}" "Ι͆"
;   "\\hat{\\Kappa}" "Κ͆"
;   "\\hat{\\Lambda}" "Λ͆"
;   "\\hat{\\Mu}" "Μ͆"
;   "\\hat{\\Nu}" "Ν͆"
;   "\\hat{\\Xi}" "Ξ͆"
;   "\\hat{\\Omicron}" "Ο͆"
;   "\\hat{\\Pi}" "Π͆"
;   "\\hat{\\Rho}" "Ρ͆"
;   "\\hat{\\Sigma}" "Σ͆"
;   "\\hat{\\Tau}" "Τ͆"
;   "\\hat{\\Upsilon}" "Υ͆"
;   "\\hat{\\Phi}" "Φ͆"
;   "\\hat{\\Chi}" "Χ͆"
;   "\\hat{\\Psi}" "Ψ͆"
;   "\\hat{\\Omega}" "Ω͆"
;
;   ; Variants and alternate forms
;   "\\hat{\\varepsilon}" "ϵ͆"
;   "\\hat{\\vartheta}" "ϑ͆"
;   "\\hat{\\varpi}" "ϖ͆"
;   "\\hat{\\varrho}" "ϱ͆"
;   "\\hat{\\varsigma}" "ς͆"
;   "\\hat{\\varphi}" "φ͆"))

((generic_command
   command: (command_name)
   arg: (curly_group)) @conceal
 (#lua-match? @conceal "\\hat{\\mathbf{[a-zA-Z]}}")
 (#set! priority 101)
 (#set-pairs! @conceal conceal
   "\\hat{\\mathbf{A}}" "𝐀̂"
   "\\hat{\\mathbf{B}}" "𝐁̂"
   "\\hat{\\mathbf{C}}" "𝐂̂"
   "\\hat{\\mathbf{D}}" "𝐃̂"
   "\\hat{\\mathbf{E}}" "𝐄̂"
   "\\hat{\\mathbf{F}}" "𝐅̂"
   "\\hat{\\mathbf{G}}" "𝐆̂"
   "\\hat{\\mathbf{H}}" "𝐇̂"
   "\\hat{\\mathbf{I}}" "𝐈̂"
   "\\hat{\\mathbf{J}}" "𝐉̂"
   "\\hat{\\mathbf{K}}" "𝐊̂"
   "\\hat{\\mathbf{L}}" "𝐋̂"
   "\\hat{\\mathbf{M}}" "𝐌̂"
   "\\hat{\\mathbf{N}}" "𝐍̂"
   "\\hat{\\mathbf{O}}" "𝐎̂"
   "\\hat{\\mathbf{P}}" "𝐏̂"
   "\\hat{\\mathbf{Q}}" "𝐐̂"
   "\\hat{\\mathbf{R}}" "𝐑̂"
   "\\hat{\\mathbf{S}}" "𝐒̂"
   "\\hat{\\mathbf{T}}" "𝐓̂"
   "\\hat{\\mathbf{U}}" "𝐔̂"
   "\\hat{\\mathbf{V}}" "𝐕̂"
   "\\hat{\\mathbf{W}}" "𝐖̂"
   "\\hat{\\mathbf{X}}" "𝐗̂"
   "\\hat{\\mathbf{Y}}" "𝐘̂"
   "\\hat{\\mathbf{Z}}" "𝐙̂"
   "\\hat{\\mathbf{a}}" "𝐚̂"
   "\\hat{\\mathbf{b}}" "𝐛̂"
   "\\hat{\\mathbf{c}}" "𝐜̂"
   "\\hat{\\mathbf{d}}" "𝐝̂"
   "\\hat{\\mathbf{e}}" "𝐞̂"
   "\\hat{\\mathbf{f}}" "𝐟̂"
   "\\hat{\\mathbf{g}}" "𝐠̂"
   "\\hat{\\mathbf{h}}" "𝐡̂"
   "\\hat{\\mathbf{i}}" "𝐢̂"
   "\\hat{\\mathbf{j}}" "𝐣̂"
   "\\hat{\\mathbf{k}}" "𝐤̂"
   "\\hat{\\mathbf{l}}" "𝐥̂"
   "\\hat{\\mathbf{m}}" "𝐦̂"
   "\\hat{\\mathbf{n}}" "𝐧̂"
   "\\hat{\\mathbf{o}}" "𝐨̂"
   "\\hat{\\mathbf{p}}" "𝐩̂"
   "\\hat{\\mathbf{q}}" "𝐪̂"
   "\\hat{\\mathbf{r}}" "𝐫̂"
   "\\hat{\\mathbf{s}}" "𝐬̂"
   "\\hat{\\mathbf{t}}" "𝐭̂"
   "\\hat{\\mathbf{u}}" "𝐮̂"
   "\\hat{\\mathbf{v}}" "𝐯̂"
   "\\hat{\\mathbf{w}}" "𝐰̂"
   "\\hat{\\mathbf{x}}" "𝐱̂"
   "\\hat{\\mathbf{y}}" "𝐲̂"
   "\\hat{\\mathbf{z}}" "𝐳̂"))

((generic_command
   command: (command_name)
   arg: (curly_group)) @conceal
 (#lua-match? @conceal "\\hat{\\mathbb{[a-zA-Z]}}")
 (#set! priority 101)
 (#set-pairs! @conceal conceal
   "\\hat{\\mathbb{A}}" "𝔸̂"
   "\\hat{\\mathbb{B}}" "𝔹̂"
   "\\hat{\\mathbb{C}}" "ℂ̂"
   "\\hat{\\mathbb{D}}" "𝔻̂"
   "\\hat{\\mathbb{E}}" "𝔼̂"
   "\\hat{\\mathbb{F}}" "𝔽̂"
   "\\hat{\\mathbb{G}}" "𝔾̂"
   "\\hat{\\mathbb{H}}" "ℍ̂"
   "\\hat{\\mathbb{I}}" "𝕀̂"
   "\\hat{\\mathbb{J}}" "𝕁̂"
   "\\hat{\\mathbb{K}}" "𝕂̂"
   "\\hat{\\mathbb{L}}" "𝕃̂"
   "\\hat{\\mathbb{M}}" "𝕄̂"
   "\\hat{\\mathbb{N}}" "ℕ̂"
   "\\hat{\\mathbb{O}}" "𝕆̂"
   "\\hat{\\mathbb{P}}" "ℙ̂"
   "\\hat{\\mathbb{Q}}" "ℚ̂"
   "\\hat{\\mathbb{R}}" "ℝ̂"
   "\\hat{\\mathbb{S}}" "𝕊̂"
   "\\hat{\\mathbb{T}}" "𝕋̂"
   "\\hat{\\mathbb{U}}" "𝕌̂"
   "\\hat{\\mathbb{V}}" "𝕍̂"
   "\\hat{\\mathbb{W}}" "𝕎̂"
   "\\hat{\\mathbb{X}}" "𝕏̂"
   "\\hat{\\mathbb{Y}}" "𝕐̂"
   "\\hat{\\mathbb{Z}}" "ℤ̂"))

((generic_command
   command: (command_name)
   arg: (curly_group)) @conceal
 (#lua-match? @conceal "\\widehat{[a-zA-Z]}")
 (#set-pairs! @conceal conceal
  "\\widehat{a}" "â"
  "\\widehat{b}" "b̂"
  "\\widehat{c}" "ĉ"
  "\\widehat{d}" "d̂"
  "\\widehat{e}" "ê"
  "\\widehat{f}" "f̂"
  "\\widehat{g}" "ĝ"
  "\\widehat{h}" "ĥ"
  "\\widehat{i}" "î"
  "\\widehat{j}" "ĵ"
  "\\widehat{k}" "k̂"
  "\\widehat{l}" "l̂"
  "\\widehat{m}" "m̂"
  "\\widehat{n}" "n̂"
  "\\widehat{o}" "ô"
  "\\widehat{p}" "p̂"
  "\\widehat{q}" "q̂"
  "\\widehat{r}" "r̂"
  "\\widehat{s}" "ŝ"
  "\\widehat{t}" "t̂"
  "\\widehat{u}" "û"
  "\\widehat{v}" "v̂"
  "\\widehat{w}" "ŵ"
  "\\widehat{x}" "x̂"
  "\\widehat{y}" "ŷ"
  "\\widehat{z}" "ẑ"
  "\\widehat{A}" "Â"
  "\\widehat{B}" "B̂"
  "\\widehat{C}" "Ĉ"
  "\\widehat{D}" "D̂"
  "\\widehat{E}" "Ê"
  "\\widehat{F}" "F̂"
  "\\widehat{G}" "Ĝ"
  "\\widehat{H}" "Ĥ"
  "\\widehat{I}" "Î"
  "\\widehat{J}" "Ĵ"
  "\\widehat{K}" "K̂"
  "\\widehat{L}" "L̂"
  "\\widehat{M}" "M̂"
  "\\widehat{N}" "N̂"
  "\\widehat{O}" "Ô"
  "\\widehat{P}" "P̂"
  "\\widehat{Q}" "Q̂"
  "\\widehat{R}" "R̂"
  "\\widehat{S}" "Ŝ"
  "\\widehat{T}" "T̂"
  "\\widehat{U}" "Û"
  "\\widehat{V}" "V̂"
  "\\widehat{W}" "Ŵ"
  "\\widehat{X}" "X̂"
  "\\widehat{Y}" "Ŷ"
  "\\widehat{Z}" "Ẑ"))

; ((generic_command
;    command: (command_name)
;    arg: (curly_group)) @conceal
;  (#lua-match? @conceal "\\widehat{\\[a-zA-Z]+}")
;  (#set! priority 101)
;  (#set-pairs! @conceal conceal
;   ; Greek letters (lowercase)
;   "\\widehat{\\alpha}" "α͆"
;   "\\widehat{\\beta}" "β͆"
;   "\\widehat{\\gamma}" "γ͆"
;   "\\widehat{\\delta}" "δ͆"
;   "\\widehat{\\epsilon}" "ε͆"
;   "\\widehat{\\zeta}" "ζ͆"
;   "\\widehat{\\eta}" "η͆"
;   "\\widehat{\\theta}" "θ͆"
;   "\\widehat{\\iota}" "ι͆"
;   "\\widehat{\\kappa}" "κ͆"
;   "\\widehat{\\lambda}" "λ͆"
;   "\\widehat{\\mu}" "μ͆"
;   "\\widehat{\\nu}" "ν͆"
;   "\\widehat{\\xi}" "ξ͆"
;   "\\widehat{\\omicron}" "ο͆"
;   "\\widehat{\\pi}" "π͆"
;   "\\widehat{\\rho}" "ρ͆"
;   "\\widehat{\\sigma}" "σ͆"
;   "\\widehat{\\tau}" "τ͆"
;   "\\widehat{\\upsilon}" "υ͆"
;   "\\widehat{\\phi}" "ϕ͆"
;   "\\widehat{\\chi}" "χ͆"
;   "\\widehat{\\psi}" "ψ͆"
;   "\\widehat{\\omega}" "ω͆"
;
;   ; Greek letters (uppercase)
;   "\\widehat{\\Alpha}" "Α͆"
;   "\\widehat{\\Beta}" "Β͆"
;   "\\widehat{\\Gamma}" "Γ͆"
;   "\\widehat{\\Delta}" "Δ͆"
;   "\\widehat{\\Epsilon}" "Ε͆"
;   "\\widehat{\\Zeta}" "Ζ͆"
;   "\\widehat{\\Eta}" "Η͆"
;   "\\widehat{\\Theta}" "Θ͆"
;   "\\widehat{\\Iota}" "Ι͆"
;   "\\widehat{\\Kappa}" "Κ͆"
;   "\\widehat{\\Lambda}" "Λ͆"
;   "\\widehat{\\Mu}" "Μ͆"
;   "\\widehat{\\Nu}" "Ν͆"
;   "\\widehat{\\Xi}" "Ξ͆"
;   "\\widehat{\\Omicron}" "Ο͆"
;   "\\widehat{\\Pi}" "Π͆"
;   "\\widehat{\\Rho}" "Ρ͆"
;   "\\widehat{\\Sigma}" "Σ͆"
;   "\\widehat{\\Tau}" "Τ͆"
;   "\\widehat{\\Upsilon}" "Υ͆"
;   "\\widehat{\\Phi}" "Φ͆"
;   "\\widehat{\\Chi}" "Χ͆"
;   "\\widehat{\\Psi}" "Ψ͆"
;   "\\widehat{\\Omega}" "Ω͆"
;
;   ; Variants and alternate forms
;   "\\widehat{\\varepsilon}" "ϵ͆"
;   "\\widehat{\\vartheta}" "ϑ͆"
;   "\\widehat{\\varpi}" "ϖ͆"
;   "\\widehat{\\varrho}" "ϱ͆"
;   "\\widehat{\\varsigma}" "ς͆"
;   "\\widehat{\\varphi}" "φ͆"))

((generic_command
   command: (command_name)
   arg: (curly_group)) @conceal
 (#lua-match? @conceal "\\widehat{\\mathbf{[a-zA-Z]}}")
 (#set! priority 101)
 (#set-pairs! @conceal conceal
   "\\widehat{\\mathbf{A}}" "𝐀̂"
   "\\widehat{\\mathbf{B}}" "𝐁̂"
   "\\widehat{\\mathbf{C}}" "𝐂̂"
   "\\widehat{\\mathbf{D}}" "𝐃̂"
   "\\widehat{\\mathbf{E}}" "𝐄̂"
   "\\widehat{\\mathbf{F}}" "𝐅̂"
   "\\widehat{\\mathbf{G}}" "𝐆̂"
   "\\widehat{\\mathbf{H}}" "𝐇̂"
   "\\widehat{\\mathbf{I}}" "𝐈̂"
   "\\widehat{\\mathbf{J}}" "𝐉̂"
   "\\widehat{\\mathbf{K}}" "𝐊̂"
   "\\widehat{\\mathbf{L}}" "𝐋̂"
   "\\widehat{\\mathbf{M}}" "𝐌̂"
   "\\widehat{\\mathbf{N}}" "𝐍̂"
   "\\widehat{\\mathbf{O}}" "𝐎̂"
   "\\widehat{\\mathbf{P}}" "𝐏̂"
   "\\widehat{\\mathbf{Q}}" "𝐐̂"
   "\\widehat{\\mathbf{R}}" "𝐑̂"
   "\\widehat{\\mathbf{S}}" "𝐒̂"
   "\\widehat{\\mathbf{T}}" "𝐓̂"
   "\\widehat{\\mathbf{U}}" "𝐔̂"
   "\\widehat{\\mathbf{V}}" "𝐕̂"
   "\\widehat{\\mathbf{W}}" "𝐖̂"
   "\\widehat{\\mathbf{X}}" "𝐗̂"
   "\\widehat{\\mathbf{Y}}" "𝐘̂"
   "\\widehat{\\mathbf{Z}}" "𝐙̂"
   "\\widehat{\\mathbf{a}}" "𝐚̂"
   "\\widehat{\\mathbf{b}}" "𝐛̂"
   "\\widehat{\\mathbf{c}}" "𝐜̂"
   "\\widehat{\\mathbf{d}}" "𝐝̂"
   "\\widehat{\\mathbf{e}}" "𝐞̂"
   "\\widehat{\\mathbf{f}}" "𝐟̂"
   "\\widehat{\\mathbf{g}}" "𝐠̂"
   "\\widehat{\\mathbf{h}}" "𝐡̂"
   "\\widehat{\\mathbf{i}}" "𝐢̂"
   "\\widehat{\\mathbf{j}}" "𝐣̂"
   "\\widehat{\\mathbf{k}}" "𝐤̂"
   "\\widehat{\\mathbf{l}}" "𝐥̂"
   "\\widehat{\\mathbf{m}}" "𝐦̂"
   "\\widehat{\\mathbf{n}}" "𝐧̂"
   "\\widehat{\\mathbf{o}}" "𝐨̂"
   "\\widehat{\\mathbf{p}}" "𝐩̂"
   "\\widehat{\\mathbf{q}}" "𝐪̂"
   "\\widehat{\\mathbf{r}}" "𝐫̂"
   "\\widehat{\\mathbf{s}}" "𝐬̂"
   "\\widehat{\\mathbf{t}}" "𝐭̂"
   "\\widehat{\\mathbf{u}}" "𝐮̂"
   "\\widehat{\\mathbf{v}}" "𝐯̂"
   "\\widehat{\\mathbf{w}}" "𝐰̂"
   "\\widehat{\\mathbf{x}}" "𝐱̂"
   "\\widehat{\\mathbf{y}}" "𝐲̂"
   "\\widehat{\\mathbf{z}}" "𝐳̂"))

((generic_command
   command: (command_name)
   arg: (curly_group)) @conceal
 (#lua-match? @conceal "\\widehat{\\mathbb{[A-Z]}}")
 (#set! priority 101)
 (#set-pairs! @conceal conceal
   "\\widehat{\\mathbb{A}}" "𝔸̂"
   "\\widehat{\\mathbb{B}}" "𝔹̂"
   "\\widehat{\\mathbb{C}}" "ℂ̂"
   "\\widehat{\\mathbb{D}}" "𝔻̂"
   "\\widehat{\\mathbb{E}}" "𝔼̂"
   "\\widehat{\\mathbb{F}}" "𝔽̂"
   "\\widehat{\\mathbb{G}}" "𝔾̂"
   "\\widehat{\\mathbb{H}}" "ℍ̂"
   "\\widehat{\\mathbb{I}}" "𝕀̂"
   "\\widehat{\\mathbb{J}}" "𝕁̂"
   "\\widehat{\\mathbb{K}}" "𝕂̂"
   "\\widehat{\\mathbb{L}}" "𝕃̂"
   "\\widehat{\\mathbb{M}}" "𝕄̂"
   "\\widehat{\\mathbb{N}}" "ℕ̂"
   "\\widehat{\\mathbb{O}}" "𝕆̂"
   "\\widehat{\\mathbb{P}}" "ℙ̂"
   "\\widehat{\\mathbb{Q}}" "ℚ̂"
   "\\widehat{\\mathbb{R}}" "ℝ̂"
   "\\widehat{\\mathbb{S}}" "𝕊̂"
   "\\widehat{\\mathbb{T}}" "𝕋̂"
   "\\widehat{\\mathbb{U}}" "𝕌̂"
   "\\widehat{\\mathbb{V}}" "𝕍̂"
   "\\widehat{\\mathbb{W}}" "𝕎̂"
   "\\widehat{\\mathbb{X}}" "𝕏̂"
   "\\widehat{\\mathbb{Y}}" "𝕐̂"
   "\\widehat{\\mathbb{Z}}" "ℤ̂"))
